### ISSUE TITLE
NameError: name 'CustomDetectionModel' is not defined

### ISSUE THREAD

**Issue by agustyawan-arif** [capjamesg/sam-clip#1]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-5-c86ea3543aac>](https://fyhm4r6nxcb-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231219-060136_RC00_592175853#) in <cell line: 12>()
     10 
     11 
---> 12 SAMCLIP = CustomDetectionModel(
     13     detection_model=GroundedSAM(
     14         CaptionOntology({"logo": "logo"})

NameError: name 'CustomDetectionModel' is not defined

**Comment by capjamesg** [comment]
Can you replace line 12 with `SAMCLIP = ComposedDetectionModel(`? I just updated the project repository as required, too. Let me know if everything works as expected!

**Comment by agustyawan-arif** [comment]
Ah I didn't see the import carefully. And hey, I suggested moving the code snippet initializing annotators before calling the `predict` function in the SAMCLIP object. So, before the line `results = SAMCLIP.predict(IMAGE)`, add these lines:

```python
annotator = sv.MaskAnnotator()
label_annotator = sv.LabelAnnotator()
```

Then, when calling the `predict` function, include the `annotator` as an argument:

```python
results = SAMCLIP.predict(IMAGE, annotator=annotator)
```

**Comment by agustyawan-arif** [comment]
Ah I didn't see the import carefully. Thanks, it works. And hey, I suggested moving the code snippet initializing annotators before calling the `predict` function in the SAMCLIP object. So, before the line `results = SAMCLIP.predict(IMAGE)`, add these lines:

```python
annotator = sv.MaskAnnotator()
label_annotator = sv.LabelAnnotator()
```

Then, when calling the `predict` function, include the `annotator` as an argument:

```python
results = SAMCLIP.predict(IMAGE, annotator=annotator)
```
